Don't use precompiled headers on MSVC 6 and 7 because it causes compilation error C2006 in freetype, which uses #include MACRO .
git-svn-id: http://svn.ghostscript.com/ghostscript/trunk@11100 a1074d23-0009-0410-80fe-cf8c14f379e6